### ISSUE TITLE
some explanations

### ISSUE THREAD

**Issue by Bennoo** [Inglebard/dockerfiles#10]
Thanks for your dockerfile
I would like to know what this part is doing because I don't understand:

`&& sed -i 's/exec .\/scripts\/on_sd_start.sh/#exec .\/scripts\/on_sd_start.sh/g' /opt/easy-diffusion/scripts/on_env_start.sh \
	&& bash start.sh \
	&& sed -i 's/#exec .\/scripts\/on_sd_start.sh/exec .\/scripts\/on_sd_start.sh/g' /opt/easy-diffusion/scripts/on_env_start.sh \
	&& cp /opt/easy-diffusion/scripts/on_sd_start.sh /opt/easy-diffusion/scripts/on_sd_start.sh.ori \
	&& cp /opt/easy-diffusion/scripts/on_env_start.sh /opt/easy-diffusion/scripts/on_env_start.sh.ori \
	&& sed -i '87,91d' /opt/easy-diffusion/scripts/on_sd_start.sh \
	&& sed -i '11,43d' /opt/easy-diffusion/scripts/on_env_start.sh \
	&& bash start.sh \
	&& mv /opt/easy-diffusion/scripts/on_sd_start.sh.ori /opt/easy-diffusion/scripts/on_sd_start.sh \
	&& mv /opt/easy-diffusion/scripts/on_env_start.sh.ori /opt/easy-diffusion/scripts/on_env_start.sh \`

I Assume this is related to a first run in order to download all the files etc but I don't understand all of these files updates.
Thanks a lot

**Comment by Inglebard** [comment]
Hi,

The default "start.sh" script execute multiple operations. They all work great at runtime but cause multiple issues to build the docker image.

The main problem is the "start.sh" which launch the webserver at the end of the execution.
The execution of the webserver is done in "on_sd_start.sh".
So I need to comment the webserver launch for the build. 

All the explanation below is only available for the v2.5.24 build (you need to refer to the v2.5.24 build archive to see the correct lines).

```
&& sed -i 's/exec .\/scripts\/on_sd_start.sh/#exec .\/scripts\/on_sd_start.sh/g' /opt/easy-diffusion/scripts/on_env_start.sh \
&& bash start.sh \
&& sed -i 's/#exec .\/scripts\/on_sd_start.sh/exec .\/scripts\/on_sd_start.sh/g' /opt/easy-diffusion/scripts/on_env_start.sh \
```
First, I need to execute "start.sh". It downloads multiple files including "on_sd_start.sh" which is missing in the first place.
To proper exit the first execution, I need to comment the execution of the file "on_sd_start.sh". I restore it afterward.


```
&& sed -i '87,91d' /opt/easy-diffusion/scripts/on_sd_start.sh \
&& sed -i '11,43d' /opt/easy-diffusion/scripts/on_env_start.sh \
&& bash start.sh \
&& mv /opt/easy-diffusion/scripts/on_sd_start.sh.ori /opt/easy-diffusion/scripts/on_sd_start.sh \
&& mv /opt/easy-diffusion/scripts/on_env_start.sh.ori /opt/easy-diffusion/scripts/on_env_start.sh \
```
Now I have access to "on_sd_start.sh". So I comment the 3 lines which launch the webserver to complete the build.
I also need to remove in "on_env_start.sh" the lines which update to hte latest version because this will remove my comment in "on_sd_start.sh".
Once done the "start.sh" script end properly and I suppose everything is downloaded for a first execution.
Like before I restore the original files.

```
&& echo '{"render_devices": "auto", "update_branch": "main", "ui": {"open_browser_on_start": false}, "net": {"listen_port": 9000,"listen_to_network": true}}' > /opt/easy-diffusion/scripts/config.json \
&& rm -r /home/user/.conda
```
Then I add some parameters to access to container and avoid launching the webbrowser which do not exist.
To gain "some space" I remove .conda which contains some temporary files.

The build is done.

On the first execution with docker, because the files has been restore, you will have the update of the file and the launch of the web server.

**Comment by Bennoo** [comment]
very clear thanks a lot!
At startup, the start.sh still download files on my side,
Do you know how I can avoid this?
do I have to launch start.sh once again before replacing by original values?

![image](https://user-images.githubusercontent.com/2066836/236452595-ddd6d568-c1a5-4b57-9b23-e1bc0c0c3581.png)

**Comment by Inglebard** [comment]
These files seems to be downloaded after the webserver is launch on the first run.
I don't think it is possible to avoid this.

If you only want to download these files once, you can use a docker volume on run.

`docker run -t -i --rm --gpus all -v cache:/home/user/.cache/ -v /dev/shm:/dev/shm -p 9000:9000 inglebard/stable-diffusion-ui `
To avoid download files in your screenshot

`docker run -t -i --rm --gpus all -v cache:/home/user/.cache/ -v easydiffusion:/opt/easy-diffusion/ -v /dev/shm:/dev/shm -p 9000:9000 inglebard/stable-diffusion-ui`
To avoid download files in your screenshot + to keep easy-diffusion up to date between each run

Please note this will take extra disk space.
