### ISSUE TITLE
I am struggling to find a way to add more cores, would like dosbox

### ISSUE THREAD

**Issue by consolecwby** [Inglebard/dockerfiles#3]

**Comment by Inglebard** [comment]
Hi,
As described in the official repo : https://github.com/libretro/RetroArch/tree/master/pkg/emscripten 
_That should be it, you can add more cores to the list by editing index.html_

In the index.html you have to edit the list, for example, you have : 
`<a class="dropdown-item" href="." data-core="genesis_plus_gx">Genesis Plus GX</a>`
The list will display : "Genesis Plus GX "and 'data-core' will load "genesis_plus_gx_libretro.wasm"
So you need to checked all the ".wasm" available (in /var/www/html of the docker image) and add it to the list.
However, I am not sure that https://buildbot.libretro.com/nightly/emscripten/ (used in the docker image) provide all cores (because https://web.libretro.com/ seems to have more), Dosbox doesn't seems to be available.

**Comment by consolecwby** [comment]
Thank you for your prompt response. I looked in that repo and was a bit overwhelmed
