### ISSUE TITLE
Building from Dockerfiles can't download from https://buildbot.libretro.com

### ISSUE THREAD

**Issue by jarrettj** [Inglebard/dockerfiles#4]
Hey,

Good day.

Tried building from the Dockerfiles for retroarch-web and retroarch-web-nightly but both fails to get the required zip files from https://buildbot.libretro.com.

Regards.
Jarrett

**Comment by Inglebard** [comment]
Hi @jarrettj ,

**For retroarch-web :**
Unfortunately, this issue is related to this news https://www.libretro.com/index.php/hacker-vandalised-our-buildbot-and-github-organization/ 

It's seems the libretro team never rebuild/restore for Emscripten. This is why the Dockerfile not working.

**For retroarch-web-nightly :**
The Dockerfile use the build from yesterday (`https://buildbot.libretro.com/nightly/emscripten/$(date -d "yesterday" '+%Y-%m-%d')_RetroArch.7z`).
However, the last build is "2020-11-18_RetroArch.7z".
If you want to build the nightly, you could edit the Dockerfile with "https://buildbot.libretro.com/nightly/emscripten/2020-11-18_RetroArch.7z".

I tried to build myself the Emscripten build without success. (lack of documentation)

To resume : 
The Dockerfiles are broken until files are present in buildbot.
I hope It will be fix with the next release.

**Comment by jarrettj** [comment]
Wow! That's crazy! Thanks for the feedback, will have a look at the nightly later. Thanks.

**Comment by Inglebard** [comment]
Hi @jarrettj ,

There is a news on retroarch :https://www.libretro.com/index.php/our-new-libretro-infrastructure-is-now-going-live-plus-dosbox-pure-out-for-androidwindows/ 

I update the dockerfile : https://github.com/Inglebard/dockerfiles/commit/774720af5249368e0464d9b02bade040f34df4c3
Nightly should work now.

And 1.9.1 is coming soon for stable.

**Comment by Inglebard** [comment]
@jarrettj 1.9.1 is available and the emscripten folder in buildbot is present.

So both stable and nightly images should work now.
I am currently pushing the 1.9.1 to Dockerhub.
